/*
 * AGC.java
 *
 * Created on January 15, 2008, 9:13 AM
 *
 * Copyright (C) 2006, 2007 by John Melton, G0ORX/N6LYT
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * The author can be reached by email at
 *
 * john.melton@sun.com
 *
 */

package radio;

/**
 *
 *  AGC
 */
public class AGC extends javax.swing.JPanel implements AGCInterface {
    
    /** Creates new form AGC */
    public AGC() {
        initComponents();
    }
    
    public void addListener(AGCListener agcListener) {
        this.agcListener=agcListener;
    }
    
    public void selected(AGCs agc) {
        switch(agc) {
            case OFF:
                agcOff.setForeground(java.awt.Color.YELLOW);
                break;
            case LONG:
                agcLong.setForeground(java.awt.Color.YELLOW);
                break;
            case SLOW:
                agcSlow.setForeground(java.awt.Color.YELLOW);
                break;
            case MEDIUM:
                agcMedium.setForeground(java.awt.Color.YELLOW);
                break;
            case FAST:
                agcFast.setForeground(java.awt.Color.YELLOW);
                break;
        }
        
    }
    
    public void unselected(AGCs agc) {
        switch(agc) {
            case OFF:
                agcOff.setForeground(java.awt.Color.BLACK);
                break;
            case LONG:
                agcLong.setForeground(java.awt.Color.BLACK);
                break;
            case SLOW:
                agcSlow.setForeground(java.awt.Color.BLACK);
                break;
            case MEDIUM:
                agcMedium.setForeground(java.awt.Color.BLACK);
                break;
            case FAST:
                agcFast.setForeground(java.awt.Color.BLACK);
                break;
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        agcOff = new javax.swing.JButton();
        agcLong = new javax.swing.JButton();
        agcSlow = new javax.swing.JButton();
        agcMedium = new javax.swing.JButton();
        agcFast = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("AGC");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        agcOff.setBackground(new java.awt.Color(153, 153, 153));
        agcOff.setText("Off");
        agcOff.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agcOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agcOffActionPerformed(evt);
            }
        });
        add(agcOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, -1));

        agcLong.setBackground(new java.awt.Color(153, 153, 153));
        agcLong.setText("Long");
        agcLong.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agcLong.setOpaque(true);
        agcLong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agcLongActionPerformed(evt);
            }
        });
        add(agcLong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, -1));

        agcSlow.setBackground(new java.awt.Color(153, 153, 153));
        agcSlow.setText("Slow");
        agcSlow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agcSlow.setOpaque(true);
        agcSlow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agcSlowActionPerformed(evt);
            }
        });
        add(agcSlow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, -1));

        agcMedium.setBackground(new java.awt.Color(153, 153, 153));
        agcMedium.setText("Medium");
        agcMedium.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agcMedium.setOpaque(true);
        agcMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agcMediumActionPerformed(evt);
            }
        });
        add(agcMedium, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 60, 20));

        agcFast.setBackground(new java.awt.Color(153, 153, 153));
        agcFast.setText("Fast");
        agcFast.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agcFast.setOpaque(true);
        agcFast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agcFastActionPerformed(evt);
            }
        });
        add(agcFast, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 60, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void agcFastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agcFastActionPerformed
        agcListener.agcSelected(AGCs.FAST);   
    }//GEN-LAST:event_agcFastActionPerformed

    private void agcMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agcMediumActionPerformed
        agcListener.agcSelected(AGCs.MEDIUM);
    }//GEN-LAST:event_agcMediumActionPerformed

    private void agcSlowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agcSlowActionPerformed
        agcListener.agcSelected(AGCs.SLOW);
    }//GEN-LAST:event_agcSlowActionPerformed

    private void agcLongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agcLongActionPerformed
        agcListener.agcSelected(AGCs.LONG);
    }//GEN-LAST:event_agcLongActionPerformed

    private void agcOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agcOffActionPerformed
        agcListener.agcSelected(AGCs.OFF);
    }//GEN-LAST:event_agcOffActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if(evt.getButton()==evt.BUTTON3) {
            agcListener.configureAGC();
        }
    }//GEN-LAST:event_formMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agcFast;
    private javax.swing.JButton agcLong;
    private javax.swing.JButton agcMedium;
    private javax.swing.JButton agcOff;
    private javax.swing.JButton agcSlow;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
    private AGCListener agcListener;
    
}
