/*
 * DisplayDialog.java
 *
 * Created on 10 May 2008, 13:36
 */

package radio;

/**
 *
 * @author  jm57878
 */
public class DisplayDialog extends javax.swing.JDialog {
    
    /** Creates new form DisplayDialog */
    public DisplayDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("java-sdr: Display Configuration");
    }
    
    public void setDisplayListener(DisplayListener listener) {
        this.displayListener=listener;
    }
    
    public void setSpectrumLow(int low) {
        spectrumLow.setSelectedItem(Integer.toString(low));
    }
    
    public void setSpectrumHigh(int high) {
        spectrumHigh.setSelectedItem(Integer.toString(high));
    }
    
    public void setWaterfallLow(int low) {
        waterfallLow.setSelectedItem(Integer.toString(low));
    }
    
    public void setWaterfallHigh(int high) {
        waterfallHigh.setSelectedItem(Integer.toString(high));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        spectrumLow = new javax.swing.JComboBox();
        spectrumHigh = new javax.swing.JComboBox();
        waterfallLow = new javax.swing.JComboBox();
        waterfallHigh = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Spectrum Low:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setText("Spectrun High:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setText("Waterfall Low:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel4.setText("Waterfall High:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        spectrumLow.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-20", "-30", "-40", "-50", "-60", "-70", "-80", "-90", "-100", "-110", "-120", "-130", "-140", "-150", "-160", "-170", "-180", "-190", "-200" }));
        spectrumLow.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                spectrumLowItemStateChanged(evt);
            }
        });
        getContentPane().add(spectrumLow, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        spectrumHigh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-20", "-30", "-40", "-50", "-60", "-70", "-80", "-90", "-100", "-110", "-120", "-130", "-140", "-150", "-160", "-170", "-180", "-190", "-200" }));
        spectrumHigh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                spectrumHighItemStateChanged(evt);
            }
        });
        getContentPane().add(spectrumHigh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        waterfallLow.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-20", "-30", "-40", "-50", "-60", "-70", "-80", "-90", "-100", "-110", "-120", "-130", "-140", "-150", "-160", "-170", "-180", "-190", "-200" }));
        waterfallLow.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                waterfallLowItemStateChanged(evt);
            }
        });
        getContentPane().add(waterfallLow, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        waterfallHigh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-20", "-30", "-40", "-50", "-60", "-70", "-80", "-90", "-100", "-110", "-120", "-130", "-140", "-150", "-160", "-170", "-180", "-190", "-200" }));
        waterfallHigh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                waterfallHighItemStateChanged(evt);
            }
        });
        getContentPane().add(waterfallHigh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void spectrumLowItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_spectrumLowItemStateChanged
        displayListener.setSpectrumLow(Integer.parseInt((String)spectrumLow.getSelectedItem()));
    }//GEN-LAST:event_spectrumLowItemStateChanged

    private void spectrumHighItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_spectrumHighItemStateChanged
        displayListener.setSpectrumHigh(Integer.parseInt((String)spectrumHigh.getSelectedItem()));
    }//GEN-LAST:event_spectrumHighItemStateChanged

    private void waterfallLowItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_waterfallLowItemStateChanged
        displayListener.setWaterfallLow(Integer.parseInt((String)waterfallLow.getSelectedItem()));
    }//GEN-LAST:event_waterfallLowItemStateChanged

    private void waterfallHighItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_waterfallHighItemStateChanged
        displayListener.setWaterfallHigh(Integer.parseInt((String)waterfallHigh.getSelectedItem()));
    }//GEN-LAST:event_waterfallHighItemStateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DisplayDialog dialog = new DisplayDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox spectrumHigh;
    private javax.swing.JComboBox spectrumLow;
    private javax.swing.JComboBox waterfallHigh;
    private javax.swing.JComboBox waterfallLow;
    // End of variables declaration//GEN-END:variables
    
    private DisplayListener displayListener;
}
