/*
 * DSP.java
 *
 * Created on September 9, 2007, 5:16 PM
 *
 * Copyright (C) 2006, 2007 by John Melton, G0ORX/N6LYT
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * The author can be reached by email at
 *
 * john.melton@sun.com
 *
 */

package radio;

import javax.security.auth.callback.Callback;

public class DSP extends javax.swing.JPanel implements DSPInterface {
    
    /** Creates new form DSP */
    public DSP() {
        initComponents();
    }
    
    public void addListener(DSPListener dspListener) {
        this.dspListener=dspListener;
    }
    
    public void selectNR(boolean state) {
        nrButton.setForeground(state?java.awt.Color.YELLOW:java.awt.Color.BLACK);
    }
    
    public void selectANF(boolean state) {
       anfButton.setForeground(state?java.awt.Color.YELLOW:java.awt.Color.BLACK);
    }
    public void selectNB(boolean state) {
        nbButton.setForeground(state?java.awt.Color.YELLOW:java.awt.Color.BLACK);
    }
    public void selectNB2(boolean state) {
        nb2Button.setForeground(state?java.awt.Color.YELLOW:java.awt.Color.BLACK);
    }
    public void selectSR(boolean state) {
        srButton.setForeground(state?java.awt.Color.YELLOW:java.awt.Color.BLACK);
    }
    public void selectBIN(boolean state) {
        binButton.setForeground(state?java.awt.Color.YELLOW:java.awt.Color.BLACK);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        nrButton = new javax.swing.JButton();
        anfButton = new javax.swing.JButton();
        nbButton = new javax.swing.JButton();
        nb2Button = new javax.swing.JButton();
        srButton = new javax.swing.JButton();
        binButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nrButton.setBackground(new java.awt.Color(153, 153, 153));
        nrButton.setText("NR");
        nrButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrButtonActionPerformed(evt);
            }
        });

        add(nrButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, -1));

        anfButton.setBackground(new java.awt.Color(153, 153, 153));
        anfButton.setText("ANF");
        anfButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        anfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anfButtonActionPerformed(evt);
            }
        });

        add(anfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 50, -1));

        nbButton.setBackground(new java.awt.Color(153, 153, 153));
        nbButton.setText("NB");
        nbButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbButtonActionPerformed(evt);
            }
        });

        add(nbButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, -1));

        nb2Button.setBackground(new java.awt.Color(153, 153, 153));
        nb2Button.setText("NB2");
        nb2Button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nb2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nb2ButtonActionPerformed(evt);
            }
        });

        add(nb2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 50, -1));

        srButton.setBackground(new java.awt.Color(153, 153, 153));
        srButton.setText("SR");
        srButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        srButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srButtonActionPerformed(evt);
            }
        });

        add(srButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, -1));

        binButton.setBackground(new java.awt.Color(153, 153, 153));
        binButton.setText("BIN");
        binButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        binButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binButtonActionPerformed(evt);
            }
        });

        add(binButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 50, -1));

        jLabel1.setText("DSP");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

    }// </editor-fold>//GEN-END:initComponents

    private void binButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binButtonActionPerformed
        dspListener.binSelected();
    }//GEN-LAST:event_binButtonActionPerformed

    private void srButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srButtonActionPerformed
        dspListener.srSelected();
    }//GEN-LAST:event_srButtonActionPerformed

    private void nb2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nb2ButtonActionPerformed
       dspListener.nb2Selected();                                    
    }//GEN-LAST:event_nb2ButtonActionPerformed

    private void nbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbButtonActionPerformed
       dspListener.nbSelected();
    }//GEN-LAST:event_nbButtonActionPerformed

    private void anfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anfButtonActionPerformed
       dspListener.anfSelected();
    }//GEN-LAST:event_anfButtonActionPerformed

    private void nrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrButtonActionPerformed
       dspListener.nrSelected();
    }//GEN-LAST:event_nrButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anfButton;
    private javax.swing.JButton binButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nb2Button;
    private javax.swing.JButton nbButton;
    private javax.swing.JButton nrButton;
    private javax.swing.JButton srButton;
    // End of variables declaration//GEN-END:variables
    
    private DSPListener dspListener;
}
