/*
 * Preamp.java
 *
 * Created on November 6, 2007, 6:25 PM
 *
 * Copyright (C) 2006, 2007 by John Melton, G0ORX/N6LYT
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * The author can be reached by email at
 *
 * john.melton@sun.com
 *
 */

package radio;

/**
 *
 *  Preamp
 */
public class Preamp extends javax.swing.JPanel implements PreampInterface{
    
    /** Creates new form Preamp */
    public Preamp() {
        initComponents();
    }
    
    
    public void addListener(PreampListener preampListener) {
        this.preampListener=preampListener;
    }
    
    public void selected(Preamps preamp) {
        switch(preamp) {
            case OFF:
                preampOff.setForeground(java.awt.Color.YELLOW);
                break;
            case LOW:
                preampLow.setForeground(java.awt.Color.YELLOW);
                break;
            case MEDIUM:
                preampMedium.setForeground(java.awt.Color.YELLOW);
                break;
            case HIGH:
                preampHigh.setForeground(java.awt.Color.YELLOW);
                break;
        }
    }
    
    public void unselected(Preamps preamp) {
        switch(preamp) {
            case OFF:
                preampOff.setForeground(java.awt.Color.BLACK);
                break;
            case LOW:
                preampLow.setForeground(java.awt.Color.BLACK);
                break;
            case MEDIUM:
                preampMedium.setForeground(java.awt.Color.BLACK);
                break;
            case HIGH:
                preampHigh.setForeground(java.awt.Color.BLACK);
                break;
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        preampOff = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        preampLow = new javax.swing.JButton();
        preampMedium = new javax.swing.JButton();
        preampHigh = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        preampOff.setBackground(new java.awt.Color(153, 153, 153));
        preampOff.setText("Off");
        preampOff.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        preampOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preampOffActionPerformed(evt);
            }
        });

        jLabel1.setText("Preamp");

        preampLow.setBackground(new java.awt.Color(153, 153, 153));
        preampLow.setText("Low");
        preampLow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        preampLow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preampLowActionPerformed(evt);
            }
        });

        preampMedium.setBackground(new java.awt.Color(153, 153, 153));
        preampMedium.setText("Medium");
        preampMedium.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        preampMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preampMediumActionPerformed(evt);
            }
        });

        preampHigh.setBackground(new java.awt.Color(153, 153, 153));
        preampHigh.setText("High");
        preampHigh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        preampHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preampHighActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(preampMedium, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .add(jLabel1)
                    .add(preampHigh, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .add(preampLow, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .add(preampOff, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(6, 6, 6)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(preampOff)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(preampLow)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(preampMedium)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(preampHigh)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void preampHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preampHighActionPerformed
        preampListener.preampSelected(Preamps.HIGH);
    }//GEN-LAST:event_preampHighActionPerformed

    private void preampMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preampMediumActionPerformed
        preampListener.preampSelected(Preamps.MEDIUM);
    }//GEN-LAST:event_preampMediumActionPerformed

    private void preampLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preampLowActionPerformed
        preampListener.preampSelected(Preamps.LOW);
    }//GEN-LAST:event_preampLowActionPerformed

    private void preampOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preampOffActionPerformed
        preampListener.preampSelected(Preamps.OFF);
    }//GEN-LAST:event_preampOffActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton preampHigh;
    private javax.swing.JButton preampLow;
    private javax.swing.JButton preampMedium;
    private javax.swing.JButton preampOff;
    // End of variables declaration//GEN-END:variables
    
    private PreampListener preampListener;
}
