/*
 * StartupDialog.java
 *
 * Created on September 9, 2007, 5:16 PM
 *
 * Copyright (C) 2006, 2007 by John Melton, G0ORX/N6LYT
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * The author can be reached by email at
 *
 * john.melton@sun.com
 *
 */

package radio;

public class StartupDialog extends javax.swing.JDialog {
    
    /** Creates new form StartupDialog */
    public StartupDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void setRadio(Radios radio) {
        this.radio=radio;
        title.setText("Java GUI for DttSP: "+radio.toString());
    }
    
    public void setStatus(String status) {
        this.status.setText(status);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        title = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        title.setFont(new java.awt.Font("Dialog", 1, 24));
        title.setText("Java GUI for DttSP: SDR1000");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        status.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        status.setBorder(null);
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 470, 40));

        jLabel2.setText("By John Melton G0ORX/N6LYT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartupDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField status;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
    
    private Radios radio;
    
}
