/*
 * TxGain.java
 *
 * Created on January 21, 2008, 8:10 AM
 *
 * Copyright (C) 2006, 2007 by John Melton, G0ORX/N6LYT
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * The author can be reached by email at
 *
 * john.melton@sun.com
 *
 */

package radio;

/**
 * 
 *  TxGain
 */
public class TxGain extends javax.swing.JPanel implements TxGainInterface {
    
    /**
     * Creates new form TxGain
     */
    public TxGain() {
        initComponents();
    }
    
    public void addListener(TxGainListener txGainListener) {
        this.txGainListener=txGainListener;
    }
    
    public void setDriveGain(int gain) {
        driveGain.setText(Integer.toString(gain));
        driveGainSlider.setValue(gain);
    }

    public void setMicGain(int gain) {
        micGain.setText(Integer.toString(gain));
        micGainSlider.setValue(gain);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        driveGainSlider = new javax.swing.JSlider();
        driveGain = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        micGainSlider = new javax.swing.JSlider();
        micGain = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Output");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        driveGainSlider.setBackground(new java.awt.Color(153, 153, 153));
        driveGainSlider.setMajorTickSpacing(25);
        driveGainSlider.setMinorTickSpacing(5);
        driveGainSlider.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        driveGainSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                driveGainSliderStateChanged(evt);
            }
        });
        add(driveGainSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 110, -1));

        driveGain.setText("jTextField1");
        driveGain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driveGainActionPerformed(evt);
            }
        });
        add(driveGain, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 40, -1));

        jLabel2.setText("Input");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        micGainSlider.setBackground(new java.awt.Color(153, 153, 153));
        micGainSlider.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        micGainSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                micGainSliderStateChanged(evt);
            }
        });
        add(micGainSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, -1));

        micGain.setText("jTextField1");
        micGain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                micGainActionPerformed(evt);
            }
        });
        add(micGain, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 40, -1));

        jLabel3.setText("DttSP TX Gain");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void micGainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_micGainActionPerformed
        int gain=Integer.parseInt(micGain.getText());
        micGainSlider.setValue(gain);
        txGainListener.txMicGainChanged(gain);
    }//GEN-LAST:event_micGainActionPerformed

    private void micGainSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_micGainSliderStateChanged
        int gain=micGainSlider.getValue();
        micGain.setText(Integer.toString(gain));
        txGainListener.txMicGainChanged(gain);
    }//GEN-LAST:event_micGainSliderStateChanged

    private void driveGainSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_driveGainSliderStateChanged
        int gain=driveGainSlider.getValue();
        driveGain.setText(Integer.toString(gain));
        txGainListener.txDriveGainChanged(gain);
    }//GEN-LAST:event_driveGainSliderStateChanged

    private void driveGainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driveGainActionPerformed
        int gain=Integer.parseInt(driveGain.getText());
        driveGainSlider.setValue(gain);
        txGainListener.txDriveGainChanged(gain);
    }//GEN-LAST:event_driveGainActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField driveGain;
    private javax.swing.JSlider driveGainSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField micGain;
    private javax.swing.JSlider micGainSlider;
    // End of variables declaration//GEN-END:variables
    
    TxGainListener txGainListener;
}
